// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: TaskInfo.proto

package taskinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 信号和Signals.py中定义的不一样
type Signal int32

const (
	Signal_SIGNAL_SEND      Signal = 0 // 发送数据信号
	Signal_SIGNAL_RECV      Signal = 1 // 接收数据信号
	Signal_SIGNAL_ACK       Signal = 2 // 确认信号（未使用，可根据需要扩展）
	Signal_SIGNAL_CHECK     Signal = 3 // 查询Cache信号
	Signal_SIGNAL_SKIP      Signal = 4 // 跳过信号
	Signal_SIGNAL_TERMINATE Signal = 9 // 终止信号
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0: "SIGNAL_SEND",
		1: "SIGNAL_RECV",
		2: "SIGNAL_ACK",
		3: "SIGNAL_CHECK",
		4: "SIGNAL_SKIP",
		9: "SIGNAL_TERMINATE",
	}
	Signal_value = map[string]int32{
		"SIGNAL_SEND":      0,
		"SIGNAL_RECV":      1,
		"SIGNAL_ACK":       2,
		"SIGNAL_CHECK":     3,
		"SIGNAL_SKIP":      4,
		"SIGNAL_TERMINATE": 9,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_TaskInfo_proto_enumTypes[0].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_TaskInfo_proto_enumTypes[0]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{0}
}

type IdTokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenNum      int32                  `protobuf:"varint,2,opt,name=token_num,json=tokenNum,proto3" json:"token_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdTokenPair) Reset() {
	*x = IdTokenPair{}
	mi := &file_TaskInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdTokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdTokenPair) ProtoMessage() {}

func (x *IdTokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdTokenPair.ProtoReflect.Descriptor instead.
func (*IdTokenPair) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{0}
}

func (x *IdTokenPair) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdTokenPair) GetTokenNum() int32 {
	if x != nil {
		return x.TokenNum
	}
	return 0
}

type TaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      int32                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Id             int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	InferWorker    int32                  `protobuf:"varint,3,opt,name=infer_worker,json=inferWorker,proto3" json:"infer_worker,omitempty"`
	CacheWorker    int32                  `protobuf:"varint,4,opt,name=cache_worker,json=cacheWorker,proto3" json:"cache_worker,omitempty"`
	TokenNum       int32                  `protobuf:"varint,5,opt,name=token_num,json=tokenNum,proto3" json:"token_num,omitempty"`
	Index          int32                  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	TaskType       int32                  `protobuf:"varint,7,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Type           string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	TaskNum        int32                  `protobuf:"varint,9,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	CachePagesList []int32                `protobuf:"varint,10,rep,packed,name=cache_pages_list,json=cachePagesList,proto3" json:"cache_pages_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_TaskInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInfo) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TaskInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskInfo) GetInferWorker() int32 {
	if x != nil {
		return x.InferWorker
	}
	return 0
}

func (x *TaskInfo) GetCacheWorker() int32 {
	if x != nil {
		return x.CacheWorker
	}
	return 0
}

func (x *TaskInfo) GetTokenNum() int32 {
	if x != nil {
		return x.TokenNum
	}
	return 0
}

func (x *TaskInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TaskInfo) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TaskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskInfo) GetTaskNum() int32 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *TaskInfo) GetCachePagesList() []int32 {
	if x != nil {
		return x.CachePagesList
	}
	return nil
}

type CombindedTaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      int32                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Id             int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	InferWorker    int32                  `protobuf:"varint,3,opt,name=infer_worker,json=inferWorker,proto3" json:"infer_worker,omitempty"`
	CacheWorker    int32                  `protobuf:"varint,4,opt,name=cache_worker,json=cacheWorker,proto3" json:"cache_worker,omitempty"`
	TokenNum       int32                  `protobuf:"varint,5,opt,name=token_num,json=tokenNum,proto3" json:"token_num,omitempty"`
	Index          int32                  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	TaskType       int32                  `protobuf:"varint,7,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Type           string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	TaskNum        int32                  `protobuf:"varint,9,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	CachePagesList []*PageList            `protobuf:"bytes,10,rep,name=cache_pages_list,json=cachePagesList,proto3" json:"cache_pages_list,omitempty"`
	IdTokenPair    []*IdTokenPair         `protobuf:"bytes,11,rep,name=id_token_pair,json=idTokenPair,proto3" json:"id_token_pair,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CombindedTaskInfo) Reset() {
	*x = CombindedTaskInfo{}
	mi := &file_TaskInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombindedTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombindedTaskInfo) ProtoMessage() {}

func (x *CombindedTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombindedTaskInfo.ProtoReflect.Descriptor instead.
func (*CombindedTaskInfo) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{2}
}

func (x *CombindedTaskInfo) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CombindedTaskInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CombindedTaskInfo) GetInferWorker() int32 {
	if x != nil {
		return x.InferWorker
	}
	return 0
}

func (x *CombindedTaskInfo) GetCacheWorker() int32 {
	if x != nil {
		return x.CacheWorker
	}
	return 0
}

func (x *CombindedTaskInfo) GetTokenNum() int32 {
	if x != nil {
		return x.TokenNum
	}
	return 0
}

func (x *CombindedTaskInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CombindedTaskInfo) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *CombindedTaskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CombindedTaskInfo) GetTaskNum() int32 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *CombindedTaskInfo) GetCachePagesList() []*PageList {
	if x != nil {
		return x.CachePagesList
	}
	return nil
}

func (x *CombindedTaskInfo) GetIdTokenPair() []*IdTokenPair {
	if x != nil {
		return x.IdTokenPair
	}
	return nil
}

type PageList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CachePagesList []int32                `protobuf:"varint,1,rep,packed,name=cache_pages_list,json=cachePagesList,proto3" json:"cache_pages_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PageList) Reset() {
	*x = PageList{}
	mi := &file_TaskInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageList) ProtoMessage() {}

func (x *PageList) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageList.ProtoReflect.Descriptor instead.
func (*PageList) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{3}
}

func (x *PageList) GetCachePagesList() []int32 {
	if x != nil {
		return x.CachePagesList
	}
	return nil
}

type TaskInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoList) Reset() {
	*x = TaskInfoList{}
	mi := &file_TaskInfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoList) ProtoMessage() {}

func (x *TaskInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoList.ProtoReflect.Descriptor instead.
func (*TaskInfoList) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfoList) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ComfirmationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComfirmationMessage) Reset() {
	*x = ComfirmationMessage{}
	mi := &file_TaskInfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComfirmationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComfirmationMessage) ProtoMessage() {}

func (x *ComfirmationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComfirmationMessage.ProtoReflect.Descriptor instead.
func (*ComfirmationMessage) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{5}
}

func (x *ComfirmationMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 空响应消息
// TODO 都要传空消息有点低效，需要优化
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_TaskInfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{6}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_TaskInfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TaskInfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_TaskInfo_proto_rawDescGZIP(), []int{7}
}

func (x *StartRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_TaskInfo_proto protoreflect.FileDescriptor

const file_TaskInfo_proto_rawDesc = "" +
	"\n" +
	"\x0eTaskInfo.proto\":\n" +
	"\vIdTokenPair\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\ttoken_num\x18\x02 \x01(\x05R\btokenNum\"\xa8\x02\n" +
	"\bTaskInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x05R\trequestId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12!\n" +
	"\finfer_worker\x18\x03 \x01(\x05R\vinferWorker\x12!\n" +
	"\fcache_worker\x18\x04 \x01(\x05R\vcacheWorker\x12\x1b\n" +
	"\ttoken_num\x18\x05 \x01(\x05R\btokenNum\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x05R\x05index\x12\x1b\n" +
	"\ttask_type\x18\a \x01(\x05R\btaskType\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x19\n" +
	"\btask_num\x18\t \x01(\x05R\ataskNum\x12(\n" +
	"\x10cache_pages_list\x18\n" +
	" \x03(\x05R\x0ecachePagesList\"\xee\x02\n" +
	"\x11CombindedTaskInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x05R\trequestId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12!\n" +
	"\finfer_worker\x18\x03 \x01(\x05R\vinferWorker\x12!\n" +
	"\fcache_worker\x18\x04 \x01(\x05R\vcacheWorker\x12\x1b\n" +
	"\ttoken_num\x18\x05 \x01(\x05R\btokenNum\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x05R\x05index\x12\x1b\n" +
	"\ttask_type\x18\a \x01(\x05R\btaskType\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x19\n" +
	"\btask_num\x18\t \x01(\x05R\ataskNum\x123\n" +
	"\x10cache_pages_list\x18\n" +
	" \x03(\v2\t.PageListR\x0ecachePagesList\x120\n" +
	"\rid_token_pair\x18\v \x03(\v2\f.IdTokenPairR\vidTokenPair\"4\n" +
	"\bPageList\x12(\n" +
	"\x10cache_pages_list\x18\x01 \x03(\x05R\x0ecachePagesList\"/\n" +
	"\fTaskInfoList\x12\x1f\n" +
	"\x05tasks\x18\x01 \x03(\v2\t.TaskInfoR\x05tasks\"'\n" +
	"\x13ComfirmationMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\" \n" +
	"\fStartRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg*s\n" +
	"\x06Signal\x12\x0f\n" +
	"\vSIGNAL_SEND\x10\x00\x12\x0f\n" +
	"\vSIGNAL_RECV\x10\x01\x12\x0e\n" +
	"\n" +
	"SIGNAL_ACK\x10\x02\x12\x10\n" +
	"\fSIGNAL_CHECK\x10\x03\x12\x0f\n" +
	"\vSIGNAL_SKIP\x10\x04\x12\x14\n" +
	"\x10SIGNAL_TERMINATE\x10\t2\xc2\x01\n" +
	"\x12InferWorkerService\x122\n" +
	"\x19ReceiveTasksFromScheduler\x12\r.TaskInfoList\x1a\x06.Empty\x12-\n" +
	"\x0fSendKVCacheData\x12\x12.CombindedTaskInfo\x1a\x06.Empty\x12-\n" +
	"\x0fRecvKVCacheData\x12\x12.CombindedTaskInfo\x1a\x06.Empty\x12\x1a\n" +
	"\bShutDown\x12\x06.Empty\x1a\x06.Empty2\x9c\x02\n" +
	"\x17CacheCoordinatorService\x124\n" +
	"\x1bReceiveTasksFromInferWorker\x12\r.TaskInfoList\x1a\x06.Empty\x12@\n" +
	"\x19ReceiveTasksFromScheduler\x12\r.TaskInfoList\x1a\x14.ComfirmationMessage\x12?\n" +
	"\x18PollBatchFromInferWorker\x12\r.TaskInfoList\x1a\x14.ComfirmationMessage\x12,\n" +
	"\x13StartProcessRequest\x12\r.StartRequest\x1a\x06.Empty\x12\x1a\n" +
	"\bShutDown\x12\x06.Empty\x1a\x06.Empty2p\n" +
	"\x0eKVCacheService\x12B\n" +
	"\x1bReceiveTasksFromCoordinator\x12\r.TaskInfoList\x1a\x14.ComfirmationMessage\x12\x1a\n" +
	"\bShutDown\x12\x06.Empty\x1a\x06.EmptyB\x10Z\x0eBi-KV/taskinfob\x06proto3"

var (
	file_TaskInfo_proto_rawDescOnce sync.Once
	file_TaskInfo_proto_rawDescData []byte
)

func file_TaskInfo_proto_rawDescGZIP() []byte {
	file_TaskInfo_proto_rawDescOnce.Do(func() {
		file_TaskInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TaskInfo_proto_rawDesc), len(file_TaskInfo_proto_rawDesc)))
	})
	return file_TaskInfo_proto_rawDescData
}

var file_TaskInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TaskInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_TaskInfo_proto_goTypes = []any{
	(Signal)(0),                 // 0: Signal
	(*IdTokenPair)(nil),         // 1: IdTokenPair
	(*TaskInfo)(nil),            // 2: TaskInfo
	(*CombindedTaskInfo)(nil),   // 3: CombindedTaskInfo
	(*PageList)(nil),            // 4: PageList
	(*TaskInfoList)(nil),        // 5: TaskInfoList
	(*ComfirmationMessage)(nil), // 6: ComfirmationMessage
	(*Empty)(nil),               // 7: Empty
	(*StartRequest)(nil),        // 8: StartRequest
}
var file_TaskInfo_proto_depIdxs = []int32{
	4,  // 0: CombindedTaskInfo.cache_pages_list:type_name -> PageList
	1,  // 1: CombindedTaskInfo.id_token_pair:type_name -> IdTokenPair
	2,  // 2: TaskInfoList.tasks:type_name -> TaskInfo
	5,  // 3: InferWorkerService.ReceiveTasksFromScheduler:input_type -> TaskInfoList
	3,  // 4: InferWorkerService.SendKVCacheData:input_type -> CombindedTaskInfo
	3,  // 5: InferWorkerService.RecvKVCacheData:input_type -> CombindedTaskInfo
	7,  // 6: InferWorkerService.ShutDown:input_type -> Empty
	5,  // 7: CacheCoordinatorService.ReceiveTasksFromInferWorker:input_type -> TaskInfoList
	5,  // 8: CacheCoordinatorService.ReceiveTasksFromScheduler:input_type -> TaskInfoList
	5,  // 9: CacheCoordinatorService.PollBatchFromInferWorker:input_type -> TaskInfoList
	8,  // 10: CacheCoordinatorService.StartProcessRequest:input_type -> StartRequest
	7,  // 11: CacheCoordinatorService.ShutDown:input_type -> Empty
	5,  // 12: KVCacheService.ReceiveTasksFromCoordinator:input_type -> TaskInfoList
	7,  // 13: KVCacheService.ShutDown:input_type -> Empty
	7,  // 14: InferWorkerService.ReceiveTasksFromScheduler:output_type -> Empty
	7,  // 15: InferWorkerService.SendKVCacheData:output_type -> Empty
	7,  // 16: InferWorkerService.RecvKVCacheData:output_type -> Empty
	7,  // 17: InferWorkerService.ShutDown:output_type -> Empty
	7,  // 18: CacheCoordinatorService.ReceiveTasksFromInferWorker:output_type -> Empty
	6,  // 19: CacheCoordinatorService.ReceiveTasksFromScheduler:output_type -> ComfirmationMessage
	6,  // 20: CacheCoordinatorService.PollBatchFromInferWorker:output_type -> ComfirmationMessage
	7,  // 21: CacheCoordinatorService.StartProcessRequest:output_type -> Empty
	7,  // 22: CacheCoordinatorService.ShutDown:output_type -> Empty
	6,  // 23: KVCacheService.ReceiveTasksFromCoordinator:output_type -> ComfirmationMessage
	7,  // 24: KVCacheService.ShutDown:output_type -> Empty
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_TaskInfo_proto_init() }
func file_TaskInfo_proto_init() {
	if File_TaskInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TaskInfo_proto_rawDesc), len(file_TaskInfo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_TaskInfo_proto_goTypes,
		DependencyIndexes: file_TaskInfo_proto_depIdxs,
		EnumInfos:         file_TaskInfo_proto_enumTypes,
		MessageInfos:      file_TaskInfo_proto_msgTypes,
	}.Build()
	File_TaskInfo_proto = out.File
	file_TaskInfo_proto_goTypes = nil
	file_TaskInfo_proto_depIdxs = nil
}
